# Debian based image that is able to run ntmsg
FROM debian:latest
MAINTAINER Manuel Ignacio Franco Galeano <maigfrga@gmail.com>

# install nodejs

RUN   apt-get update -y
RUN   apt-get install -y nodejs npm
RUN npm  install   aws-sdk lodash winston commander

USER daemon

# Add
ADD app /opt/app


 AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}}
ENV AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}}


CMD [ "nodejs", "/opt/app/worker.js",  "--config",  "/opt/app/config.json"]
